#!/bin/sh

case $1 in
"dim"*)
  echo 100 > /sys/class/backlight/intel_backlight/brightness
  ;;
"normal")
  echo 400 > /sys/class/backlight/intel_backlight/brightness
  ;;
"bright")
  echo 851 > /sys/class/backlight/intel_backlight/brightness
  ;;
*)
  echo "Usage: brightness.sh (dim|normal|bright)"
  exit 1
  ;;
esac